export const coffees = [
  {
    id: "1",
    title: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    tags: ["TRADICIONAL"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/expresso.svg",
  },
  {
    id: "2",
    title: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    tags: ["TRADICIONAL"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/americano.svg",
  },
  {
    id: "3",
    title: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    tags: ["TRADICIONAL"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/expresso-cremoso.svg",
  },
  {
    id: "4",
    title: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    tags: ["TRADICIONAL", "GELADO"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/cafe-gelado.svg",
  },
  {
    id: "5",
    title: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    tags: ["TRADICIONAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/cafe-com-leite.svg",
  },
  {
    id: "6",
    title: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    tags: ["TRADICIONAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/latte.svg",
  },
  {
    id: "7",
    title: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    tags: ["TRADICIONAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/capuccino.svg",
  },
  {
    id: "8",
    title: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    tags: ["TRADICIONAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/macchiato.svg",
  },
  {
    id: "9",
    title: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    tags: ["TRADICIONAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/mocaccino.svg",
  },
  {
    id: "10",
    title: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    tags: ["ESPECIAL", "COM LEITE"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/chocolate-quente.svg",
  },
  {
    id: "11",
    title: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    tags: ["ESPECIAL", "ALCOÓLICO", "GELADO"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/cubano.svg",
  },
  {
    id: "12",
    title: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    tags: ["ESPECIAL"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/havaiano.svg",
  },
  {
    id: "13",
    title: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    tags: ["ESPECIAL"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/arabe.svg",
  },
  {
    id: "14",
    title: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    tags: ["ESPECIAL", "ALCOÓLICO"],
    price: 9.9,
    quantity: 0,
    image: "src/assets/coffee/irlandes.svg",
  },
];
